### ISSUE TITLE
Make useful metrics

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/sce-domain-discovery#2] opened 2017-06-14 21:45 UTC
Either make Accuracy mean something or replace it with something else useful, eg Number of Highly Relevant, Relevant, and Not Relevant pages that have been marked.

**Comment by giuseppetotaro** [comment] 2017-06-15 06:35
Commit number 02cb06022b08f44121fad0731ccaeac448361518 removes the accuracy from the WebUI as it is currently useless.

**Comment by giuseppetotaro** [comment] 2017-06-19 21:22
Basically we need to show the statistics on how many high relevant, relevant, and not relevant results have been marked by user with respect to a specific model.

**Comment by giuseppetotaro** [comment] 2017-06-23 08:09
This is a duplicate of issue #10.

**Closed by giuseppetotaro** 2017-06-23 08:09 UTC
